- name: install docker on nodes
  hosts: web
  remote_user: root
  become: yes
  tasks:
    - name: update cache and install packages
      apt:
        update_cache: yes
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl 
        - gnupg-agent
        - software-properties-common
    
    - name: add docker gpg key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        update_cache: yes

    - name: install docker engine
      apt:
        update_cache: yes
        pkg:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      notify: restart docker

    - name: add ubuntu to docker group
      user:
        name: ubuntu
        append: yes
        groups: docker

    - name: run nginx
      shell:
        cmd: docker run -d -p 8080:80 nginx
  
  handlers:  
    - name: restart docker
      systemd:
        name: docker
        state: restarted
